/* eslint-disable  func-names */
/* eslint-disable max-len */
/* eslint quote-props: ['error', 'consistent']*/
module.exports = {
    'RECIPE_EN_US': {
        'dark willow': 'Ember spirit, invoker, juggernaut, lina, mirana, phoenix, puck, warlock and weaver.',
        'pangolier': 'Abbadon, ancient apparition, bat rider, brew master, clock werk, drow ranger, earth spirit, jakiro medusa and undying.',
        'winter wyvern': 'Dark seer, enigma, magnus and venomancer.',
        'visage': 'Drow ranger, slardar, life stealer, beast master and elder titan.',
        'shadow demon': 'Ancient apparition, dazzle, luna, terror blade and warlock.',
        'outworld devourer': 'Omni knight, ogre magi and winter wyvern.',
        'invoker': 'Blood seeker, dark seer, disruptor, nature\'s prophet, faceless void and legion commander.',
        'ancient apparition': 'Meepo, phantom assassin, shadow demon, slark and ursa.',
        'bat rider': 'Ursa, pugna, skywrath mage and pudge.',
        'dark seer': 'Bounty hunter, elder titan, riki, luna, sven and venomancer.',
        'leshrac': 'Dark seer, enigma and magnus.',
        'dazzle': 'Brew master, brood mother, huskar, meepo, naga siren and phantom lancer.',
        'pugna': 'Io, legion commander, necrophos, medusa, skywrath mage and shadow shaman.',
        'death prophet': 'Faceless void, enigma and nature\'s prophet.',
        'queen of pain': 'Axe, dark seer, enigma, faceless void, life stealer, magnus and omni knight.',
        'warlock': 'none.',
        'necrophos': 'none.',
        'enigma': 'none.',
        'lion': 'none.',
        'witch doctor': 'none.',
        'lich': 'none.',
        'bane': 'none.',
        'techies': 'none.',
        'oracle': 'none.',
        'skywrath mage': 'none.',
        'keeper of the light': 'none.',
        'rubick': 'none.',
        'disruptor': 'none.',
        'ogre magi': 'none.',
        'silencer': 'none.',
        'chen': 'none.',
        'jakiro': 'none.',
        'enchantress': 'none.',
        'nature\'s prophet': 'none.',
        'tinker': 'none.',
        'shadow shaman': 'none.',
        'lina': 'none.',
        'zeus': 'none.',
        'wind ranger': 'none.',
        'storm spirit': 'none.',
        'puck': 'none.',
        'crystal maiden': 'none.',
        'arc warden': 'none.',
        'terror blade': 'none.',
        'medusa': 'none.',
        'slark': 'none.',
        'nyx assassin': 'none.',
        'meepo': 'none.',
        'spectre': 'none.',
        'weaver': 'none.',
        'brood mother': 'none.',
        'clinkz': 'none.',
        'viper': 'none.',
        'phantom assassin': 'none.',
        'faceless void': 'none.',
        'venomancer': 'none.',
        'razor': 'none.',
        'shadow fiend': 'none.',
        'blood seeker': 'none.',
        'monkey king': 'none.',
        'ember spirit': 'none.',
        'troll warlord': 'none.',
        'naga siren': 'none.',
        'lone druid': 'none.',
        'gyro copter': 'none.',
        'ursa': 'none.',
        'bounty hunter': 'none.',
        'luna': 'none.',
        'templar assassin': 'none.',
        'sniper': 'none.',
        'riki': 'none.',
        'vengeful spirit': 'none.',
        'phantom lancer': 'none.',
        'morphling': 'none.',
        'mirana': 'none.',
        'juggernaut': 'none.',
        'drow ranger': 'none.',
        'anti mage': 'none.',
        'under lord': 'none.',
        'abaddon': 'none.',
        'magnus': 'none.',
        'undying': 'none.',
        'chaos knight': 'none.',
        'lycan': 'none.',
        'spirit breaker': 'none.',
        'doom': 'none.',
        'night stalker': 'none.',
        'life stealer': 'none.',
        'wraith king': 'none.',
        'tide hunter': 'none.',
        'slardar': 'none.',
        'sand king': 'none.',
        'pudge': 'none.',
        'axe': 'none.',
        'phoenix': 'none.',
        'earth spirit': 'none.',
        'legion commander': 'none.',
        'elder titan': 'none.',
        'tusk': 'none.',
        'bristle back': 'none.',
        'timber saw': 'none.',
        'centaur warrunner': 'none.',
        'io': 'none.',
        'treant protector': 'none.',
        'brew master': 'none.',
        'alchemist': 'none.',
        'huskar': 'none.',
        'omni knight': 'none.',
        'clock werk': 'none.',
        'dragon knight': 'none.',
        'beast master': 'none.',
        'kunkaa': 'none.',
        'tiny': 'none.',
        'sven': 'none.',
        'earth shaker': 'none.',
    },
};