/* eslint-disable  func-names */
/* eslint-disable max-len */
/* eslint quote-props: ['error', 'consistent']*/
module.exports = {
    'RECIPE_EN_US': {
        'dark willow': 'Anti mage, bristle back, ember spirit, huskar, juggernaut, life stealer, nyx assassin, omni knight, oracle, puck, pudge, riki, silencer and storm spirit.',
        'pangolier': 'Anti mage, beast master, blood seeker, centaur warrunner, doom, faceless void, medusa, naga siren, omni knight, outworld devourer, queen of pain, spirit breaker, storm spirit, treant protector and vengeful spirit.',
		'winter wyvern': 'invoker, luna, omni knight, outworld devourer, pugna, skywrath mage, slark, timber saw, tinker and undying.',
		'visage': 'Axe, gyro copter, luna, rubick, timber saw and tide hunter.',
		'shadow demon': 'Ember spirit, leshrac, oracle, storm spirit and lion.',
		'outworld devourer': 'Brew master, legion commander, lone druid, nyx assassin, pugna, silencer, sniper and templar assassin.',
		'invoker': 'Anti mage, doom, faceless void, huskar, night stalker, nyx assassin, queen of pain, silencer, storm spirit, templar assassin and viper.',
		'ancient apparition': 'Anti mage, oracle, phantom lancer, phoenix, terror blade, viper and weaver.',
		'bat rider': 'Abbadon, kunkaa, legion commander, nyx assassin oracle, tide hunter, ursa, vengeful spirit, venomancer, weaver and slark.',
		'dark seer': 'Anti mage, ember spirit, keeper of the light, oracle and sniper.',
		'leshrac': 'Pugna, anti mage, clock werk, life stealer, nyx assassin and keeper of the light.',
		'dazzle': 'Axe, silencer, ancient apparition, outworld devourer, naga siren and phantom lancer.',
		'pugna': 'Nyx assassin, clock werk, sniper, phantom lancer, anti mage and luna.',
		'death prophet': 'Anti mage, doom, legion commander, phantom lancer and tinker.',
		'queen of pain': 'Alchemist, anti mage, arc warden, bloodseeker, death prophet, disruptor, luna, meepo, night stalker, nyx assassin, puck and skywrath mage.',
		'warlock': 'Weaver, anti mage, blood seeker, silencer, dark seer and ember spirit.',
		'necrophos': 'Abbadon, ancient apparition, anti mage, dazzle, meepo, omni knight, oracle, phantom lancer, riki and rubick.',
		'enigma': 'none.',
		'lion': 'none.',
		'witch doctor': 'none.',
		'lich': 'none.',
		'bane': 'none.',
		'techies': 'none.',
		'oracle': 'none.',
		'skywrath mage': 'none.',
		'keeper of the light': 'none.',
		'rubick': 'none.',
		'disruptor': 'none.',
		'ogre magi': 'none.',
		'silencer': 'none.',
		'chen': 'none.',
		'jakiro': 'none.',
		'enchantress': 'none.',
		'nature\'s prophet': 'none.',
		'tinker': 'none.',
		'shadow shaman': 'none.',
		'lina': 'none.',
		'zeus': 'none.',
		'wind ranger': 'none.',
		'storm spirit': 'none.',
		'puck': 'none.',
		'crystal maiden': 'none.',
		'arc warden': 'none.',
		'terror blade': 'none.',
		'medusa': 'none.',
		'slark': 'none.',
		'nyx assassin': 'none.',
		'meepo': 'none.',
		'spectre': 'none.',
		'weaver': 'none.',
		'brood mother': 'none.',
		'clinkz': 'none.',
		'viper': 'none.',
		'phantom assassin': 'none.',
		'faceless void': 'none.',
		'venomancer': 'none.',
		'razor': 'none.',
		'shadow fiend': 'none.',
		'blood seeker': 'none.',
		'monkey king': 'none.',
		'ember spirit': 'none.',
		'troll warlord': 'none.',
		'naga siren': 'none.',
		'lone druid': 'none.',
		'gyro copter': 'none.',
		'ursa': 'none.',
		'bounty hunter': 'none.',
		'luna': 'none.',
		'templar assassin': 'none.',
		'sniper': 'none.',
		'riki': 'none.',
		'vengeful spirit': 'none.',
		'phantom lancer': 'none.',
		'morphling': 'none.',
		'mirana': 'none.',
		'juggernaut': 'none.',
		'drow ranger': 'none.',
		'anti mage': 'none.',
		'under lord': 'none.',
		'abaddon': 'none.',
		'magnus': 'none.',
		'undying': 'none.',
		'chaos knight': 'none.',
		'lycan': 'none.',
		'spirit breaker': 'none.',
		'doom': 'none.',
		'night stalker': 'none.',
		'life stealer': 'none.',
		'wraith king': 'none.',
		'tide hunter': 'none.',
		'slardar': 'none.',
		'sand king': 'none.',
		'pudge': 'none.',
		'axe': 'none.',
		'phoenix': 'none.',
		'earth spirit': 'none.',
		'legion commander': 'none.',
		'elder titan': 'none.',
		'tusk': 'none.',
		'bristle back': 'none.',
		'timber saw': 'none.',
		'centaur warrunner': 'none.',
		'io': 'none.',
		'treant protector': 'none.',
		'brew master': 'none.',
		'alchemist': 'none.',
		'huskar': 'none.',
		'omni knight': 'none.',
		'clock werk': 'none.',
		'dragon knight': 'none.',
		'beast master': 'none.',
		'kunkaa': 'none.',
		'tiny': 'none.',
		'sven': 'none.',
		'earth shaker': 'none.',
    },
};